### ISSUE TITLE
GZIP Compression has invalid content length

### ISSUE THREAD

**Issue by Jorricks** [Jorricks/DutyBoard#5]
Currently when we are using the production version where the GZIPs are already pre-computed, the GZIPS response header for `content-length` is invalid. As the value is based on the non-GZIPPED file.
This also yields the following exception in the webserver;
```
INFO:     172.16.223.89:40306 - "GET /main.77b972f2406e89fc2985.css HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/bigdata/venv/lib64/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/bigdata/venv/lib64/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/bigdata/venv/lib64/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/staticfiles.py", line 102, in __call__
    await response(scope, receive, send)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/responses.py", line 354, in __call__
    await send(
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 520, in send
    output = self.conn.send(event)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/h11/_writers.py", line 67, in __call__
    self.send_eom(event.headers, write)
  File "/home/bigdata/venv/lib64/python3.9/site-packages/h11/_writers.py", line 96, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

**Comment by Jorricks** [comment]
Fixed in [0.0.1a7](https://github.com/Jorricks/DutyBoard/releases/tag/0.0.1a7)
